 export default [
    {
    "id": 2506,
    "firstName": "Baalaaditya Bhattathiri",
    "email": "baalaaditya_bhattathiri@rowe-marquardt.org",
    "gender": "female",
    "status": "inactive",
    "password": "12345",
    "lastName": 'Mishra',
    "designation":'coder',
    "dateOfBirth": '24/06/1987',
    "country":"India"
    },
    {
    "id": 2505,
    "firstName": "Fr. Annapurna Dhawan",
    "email": "annapurna_fr_dhawan@ruecker.co",
    "gender": "male",
    "status": "active",
    "password": "12345",
    "lastName": 'Mishra',
    "designation":'coder',
    "dateOfBirth": '24/06/1987',
    "country":"India"
    },
    {
    "id": 2504,
    "firstName": "Umang Iyengar",
    "email": "umang_iyengar@turner.com",
    "gender": "female",
    "status": "inactive",
    "password": "12345",
    "lastName": 'Mishra',
    "designation":'coder',
    "dateOfBirth": '24/06/1987',
    "country":"India"
    },
    {
    "id": 2503,
    "firstName": "Chakravartee Nayar",
    "email": "chakravartee_nayar@buckridge.biz",
    "gender": "male",
    "status": "inactive",
    "password": "12345",
    "lastName": 'Mishra',
    "designation":'coder',
    "dateOfBirth": '24/06/1987',
    "country":"India"
    },
    {
    "id": 2502,
    "firstName": "Mahesh Rana VM",
    "email": "vm_mahesh_rana@kuhn.org",
    "gender": "male",
    "status": "active",
    "password": "12345",
    "lastName": 'Mishra',
    "designation":'coder'
    },
    {
    "id": 2501,
    "firstName": "Chanda Gandhi",
    "email": "gandhi_chanda@beer.net",
    "gender": "male",
    "status": "active",
    "password": "12345",
    "lastName": 'Mishra',
    "designation":'coder',
    "dateOfBirth": '24/06/1987',
    "country":"India"
    },
    {
    "id": 2500,
    "firstName": "Sarala Kaul",
    "email": "kaul_sarala@lueilwitz-konopelski.org",
    "gender": "male",
    "status": "active",
    "password": "12345",
    "lastName": 'Mishra',
    "designation":'coder',
    "dateOfBirth": '24/06/1987',
    "country":"India"
    },
    {
    "id": 2499,
    "firstName": "Bhupen Rana PhD",
    "email": "phd_rana_bhupen@cole.co",
    "gender": "female",
    "status": "active",
    "password": "12345",
    "lastName": 'Mishra',
    "designation":'coder',
    "dateOfBirth": '24/06/1987',
    "country":"India"
    },
    {
    "id": 2498,
    "firstName": "Chidambaram Sinha",
    "email": "chidambaram_sinha@wilkinson-spinka.biz",
    "gender": "female",
    "status": "active",
    "password": "12345",
    "lastName": 'Mishra',
    "designation":'coder',
    "dateOfBirth": '24/06/1987',
    "country":"India"
    },
    {
    "id": 2497,
    "firstName": "Ms. Annapurna Prajapat",
    "email": "annapurna_prajapat_ms@willms.name",
    "gender": "male",
    "status": "active",
    "password": "12345",
    "lastName": 'Mishra',
    "designation":'coder',
    "dateOfBirth": '24/06/1987',
    "country":"India"
    }
    ]